export const BookTags = [
  { name: 'Fantasy', color: '#B04B4B' },
  { name: 'Science fiction', color: '#FF7F50' },
  { name: 'Dystopian', color: '#4B384B' },
  { name: 'Action and adventure', color: '#1B6B6B' },
  { name: 'Detective and mystery', color: '#A0B040' },
  { name: 'Thriller and suspense', color: '#408080' },
  { name: 'Romance', color: '#E5398B' },
  { name: 'Horror', color: '#303030' },
  { name: 'Historical fiction', color: '#8B4B8B' },
  { name: 'Contemporary fiction', color: '#6A5ACD' },
  { name: 'Graphic novels', color: '#FFD700' },
  { name: 'Short story', color: '#556B2F' },
  { name: 'Biography', color: '#87CEEB' },
  { name: 'History', color: '#CD853F' },
  { name: 'Food and drink', color: '#9ACD32' },
  { name: 'Poetry', color: '#C0DD00' },
  { name: 'True crime', color: '#483D8B' },
  { name: 'Art and photography', color: '#FF6347' },
  { name: 'Essays', color: '#8B4513' },
  { name: 'Science and technology', color: '#20B2AA' },
  { name: 'Novel', color: '#6495ED' },
  { name: 'Terror', color: '#8B0000' },
  { name: 'Self-help', color: '#A9A9A9' },
  { name: 'Travel', color: '#F08080' },
];
