export const BookTags = [
  { name: 'Fantasy', color: '#ffcdd2' },
  { name: 'Science fiction', color: '#ef5350' },
  { name: 'Dystopian', color: '#b71c1c' },
  { name: 'Action and adventure', color: '#f8bbd0' },
  { name: 'Romance', color: '#ec407a' },
  { name: 'LGBT', color: '#880e4f' },
  { name: 'Novel', color: '#e1bee7' },
  { name: 'Historical fiction', color: '#ba68c8' },
  { name: 'Contemporary fiction', color: '#4a148c' },
  { name: 'Terror', color: '#b39ddb' },
  { name: 'Mistery', color: '#673ab7' },
  { name: 'Horror', color: '#311b92' },
  { name: 'Thriller and suspense', color: '#9fa8da' },
  { name: 'Biography', color: '#3f51b5' },
  { name: 'Self-help', color: '#1a237e' },
  { name: 'Travel', color: '#90caf9' },
];
